hyperskill_project:
  id: 78
  ide_files: https://stepik.org/media/attachments/lesson/255033/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 26 Aug 2021 15:00:35 UTC
stages:
- id: 431
  step: 7205
  is_completed: true
- id: 432
  step: 7206
  is_completed: true
- id: 433
  step: 7207
  is_completed: true
- id: 434
  step: 7208
  is_completed: true
- id: 435
  step: 7209
  is_completed: true
topics:
  0:
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Naming variables
    theory_id: 5885
  - title: Taking input
    theory_id: 5913
  - title: Program with numbers
    theory_id: 5872
  - title: If statement
    theory_id: 5953
  - title: Else statement
    theory_id: 5932
  - title: Elif statement
    theory_id: 5926
  - title: Basic data types
    theory_id: 5852
  - title: Integer arithmetic
    theory_id: 5865
  - title: Variables
    theory_id: 5859
  - title: Boolean logic
    theory_id: 6025
  - title: Comparisons
    theory_id: 5920
  1:
  - title: IDE
    theory_id: 10996
  - title: Load module
    theory_id: 6019
  - title: Random module
    theory_id: 6263
  - title: PyCharm basics
    theory_id: 6193
  - title: Quotes and multi-line strings
    theory_id: 5814
  - title: String formatting
    theory_id: 6037
  - title: List
    theory_id: 5979
  - title: Invoking a function
    theory_id: 5891
  - title: Dictionary
    theory_id: 6481
  2:
  - title: Avoiding bad comments
    theory_id: 6440
  - title: While loop
    theory_id: 5940
  - title: For loop
    theory_id: 6065
  - title: Loop control statements
    theory_id: 6302
  3:
  - title: Introduction to operating systems
    theory_id: 9704
  - title: Files
    theory_id: 13025
  - title: File types
    theory_id: 13017
  - title: Intro to computational thinking
    theory_id: 8742
  - title: Components of computational thinking
    theory_id: 8745
  - title: Sep and end arguments of print
    theory_id: 7452
  - title: Command line overview
    theory_id: 8977
  - title: Introduction to Linux
    theory_id: 9526
  - title: File modes and permissions
    theory_id: 13953
  - title: Working with file modes and permissions
    theory_id: 13961
  - title: Files in Python
    theory_id: 8691
  - title: Reading files
    theory_id: 8139
  - title: Writing files
    theory_id: 8334
  - title: Flush and file arguments of print
    theory_id: 8006
  - title: Declaring a function
    theory_id: 5900
  - title: Arguments
    theory_id: 7248
  - title: Functional decomposition
    theory_id: 9571
  4:
  - title: Escape sequences
    theory_id: 7130
  - title: Indexes
    theory_id: 6189
  - title: Slicing
    theory_id: 6177
  - title: Basic string methods
    theory_id: 6842
  - title: Operations with list
    theory_id: 6031
  - title: Split and join
    theory_id: 6972
